# Generated by Django 5.2.8 on 2025-12-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='category',
            field=models.CharField(choices=[('primary', '小学'), ('middle', '初中'), ('high', '高中'), ('university', '大学'), ('other', '其他')], default='other', max_length=20, verbose_name='学校类型'),
        ),
        migrations.AddField(
            model_name='school',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='school',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='区县'),
        ),
        migrations.AddField(
            model_name='school',
            name='province',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='省份'),
        ),
    ]
