# Generated by Django 5.2.7 on 2025-11-05 02:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='分数')),
                ('class_rank', models.IntegerField(blank=True, null=True, verbose_name='班级排名')),
                ('grade_rank', models.IntegerField(blank=True, null=True, verbose_name='年级排名')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '成绩',
                'verbose_name_plural': '成绩',
                'db_table': 'scores',
                'ordering': ['-exam__exam_date', 'student__class_obj__grade', 'student__class_obj__class_number'],
            },
        ),
    ]
