# Generated by Django 5.2.8 on 2025-11-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', '超级管理员'), ('admin', '普通管理员'), ('head_teacher', '班主任'), ('subject_teacher', '任课教师')], default='subject_teacher', max_length=20, verbose_name='角色'),
        ),
    ]
