# Generated by Django 5.2.7 on 2025-11-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_role',
            field=models.CharField(blank=True, choices=[('super_admin', '超级管理员'), ('admin', '普通管理员'), ('head_teacher', '班主任'), ('subject_teacher', '任课教师')], help_text='用户当前激活使用的角色', max_length=20, null=True, verbose_name='当前角色'),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.JSONField(blank=True, default=list, help_text='用户拥有的所有角色列表，如 ["admin", "head_teacher"]', verbose_name='所有角色'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', '超级管理员'), ('admin', '普通管理员'), ('head_teacher', '班主任'), ('subject_teacher', '任课教师')], default='subject_teacher', max_length=20, verbose_name='主要角色'),
        ),
    ]
