# Generated by Django 5.2.8 on 2025-12-09 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_current_role_user_roles_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(unique=True, verbose_name='Token')),
                ('status', models.CharField(choices=[('waiting', '等待扫描'), ('scanned', '已扫描'), ('confirmed', '已确认'), ('expired', '已过期')], default='waiting', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='确认用户')),
            ],
            options={
                'verbose_name': '登录二维码',
                'verbose_name_plural': '登录二维码',
                'db_table': 'login_qrcodes',
                'ordering': ['-created_at'],
            },
        ),
    ]
