# Generated by Django 5.2.8 on 2025-12-09 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_loginqrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=64, unique=True, verbose_name='设备唯一标识')),
                ('name', models.CharField(max_length=50, verbose_name='设备名称')),
                ('last_heartbeat', models.DateTimeField(auto_now=True, verbose_name='最后活跃时间')),
                ('pending_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='登录Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_devices', to=settings.AUTH_USER_MODEL, verbose_name='绑定用户')),
            ],
            options={
                'verbose_name': '远程设备',
                'verbose_name_plural': '远程设备',
                'db_table': 'remote_devices',
                'ordering': ['-created_at'],
            },
        ),
    ]
