# Generated by Django 5.2.8 on 2025-12-09 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remotedevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotedevice',
            name='last_agent_heartbeat',
            field=models.DateTimeField(blank=True, null=True, verbose_name='助手活跃时间'),
        ),
        migrations.AddField(
            model_name='remotedevice',
            name='pending_command',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='控制指令'),
        ),
        migrations.AlterField(
            model_name='remotedevice',
            name='last_heartbeat',
            field=models.DateTimeField(auto_now=True, verbose_name='网页活跃时间'),
        ),
    ]
