# Generated by Django 5.2.8 on 2025-12-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_emailverification_user_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotedevice',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='是否锁定'),
        ),
    ]
