# Generated by Django 5.2.8 on 2025-12-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remotedevice_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotedevice',
            name='file_server_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='文件服务器地址'),
        ),
        migrations.AddField(
            model_name='remotedevice',
            name='media_server_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='媒体服务器地址'),
        ),
    ]
