# Generated by Django 5.2.8 on 2026-01-25 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_category_school_city_school_district_and_more'),
        ('users', '0010_remotedevice_file_server_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WechatVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('code', models.CharField(blank=True, default='', max_length=6, verbose_name='验证码')),
                ('openid', models.CharField(blank=True, default='', max_length=64, verbose_name='微信OpenID')),
                ('type', models.CharField(choices=[('register', '注册'), ('reset_password', '重置密码')], default='register', max_length=20, verbose_name='验证类型')),
                ('is_verified', models.BooleanField(default=False, verbose_name='是否已验证')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '微信验证码',
                'verbose_name_plural': '微信验证码',
                'db_table': 'wechat_verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已拒绝'), ('blocked', '已封禁')], default='pending', max_length=20, verbose_name='状态')),
                ('migrate_classes', models.BooleanField(default=False, verbose_name='迁移班级')),
                ('migrate_students', models.BooleanField(default=False, verbose_name='迁移学生')),
                ('reject_count', models.IntegerField(default=0, verbose_name='拒绝次数')),
                ('reject_reason', models.TextField(blank=True, default='', verbose_name='拒绝原因')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='schools.school', verbose_name='目标学校')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请教师')),
            ],
            options={
                'verbose_name': '学校加入申请',
                'verbose_name_plural': '学校加入申请',
                'db_table': 'school_join_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherSchoolMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_memberships', to='schools.school', verbose_name='学校')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_memberships', to=settings.AUTH_USER_MODEL, verbose_name='教师')),
            ],
            options={
                'verbose_name': '教师学校关系',
                'verbose_name_plural': '教师学校关系',
                'db_table': 'teacher_school_memberships',
                'unique_together': {('teacher', 'school')},
            },
        ),
    ]
