# Generated by Django 5.2.8 on 2026-01-25 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_wechatverification_schooljoinrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_demo_account',
            field=models.BooleanField(default=False, help_text='演示账号不能修改密码，其班级和学生数据不能被删除', verbose_name='演示账号'),
        ),
    ]
