# Generated by Django 5.2.8 on 2026-01-26 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_is_demo_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wechat_openid',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='微信OpenID'),
        ),
        migrations.AddField(
            model_name='wechatverification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wechat_verifications', to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
        ),
        migrations.AlterField(
            model_name='wechatverification',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='wechatverification',
            name='type',
            field=models.CharField(choices=[('register', '注册'), ('reset_password', '重置密码'), ('bind', '绑定账号')], default='register', max_length=20, verbose_name='验证类型'),
        ),
    ]
