# Generated by Django 5.2.8 on 2026-02-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_wechat_openid_wechatverification_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dashboard_cards',
            field=models.JSONField(blank=True, default=dict, help_text='按角色存储的桌面快捷卡片，如 {"admin": ["card-id-1", "card-id-2"]}', verbose_name='桌面卡片配置'),
        ),
    ]
