# Generated by Django 5.2.8 on 2026-02-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_add_dashboard_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_role',
            field=models.CharField(blank=True, choices=[('super_admin', '超级管理员'), ('admin', '普通管理员'), ('head_teacher', '班主任'), ('subject_teacher', '任课教师'), ('student', '学生')], help_text='用户当前激活使用的角色', max_length=20, null=True, verbose_name='当前角色'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', '超级管理员'), ('admin', '普通管理员'), ('head_teacher', '班主任'), ('subject_teacher', '任课教师'), ('student', '学生')], default='subject_teacher', max_length=20, verbose_name='主要角色'),
        ),
    ]
