# Generated by Django 5.2.7 on 2025-11-05 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='考试名称')),
                ('exam_type', models.CharField(choices=[('monthly', '月考'), ('midterm', '期中考试'), ('final', '期末考试'), ('quiz', '测验'), ('other', '其他')], default='monthly', max_length=20, verbose_name='考试类型')),
                ('academic_year', models.CharField(default='2024-2025', max_length=20, verbose_name='学年')),
                ('semester', models.CharField(default='第二学期', max_length=10, verbose_name='学期')),
                ('exam_date', models.DateField(verbose_name='考试日期')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='结束时间')),
                ('applicable_grades', models.JSONField(default=list, help_text='例如：[1,2,3,4,5,6] 表示适用于所有年级', verbose_name='适用年级')),
                ('score_deadline', models.DateTimeField(blank=True, null=True, verbose_name='成绩录入截止时间')),
                ('description', models.TextField(blank=True, null=True, verbose_name='考试说明')),
                ('is_published', models.BooleanField(default=False, verbose_name='是否公布')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('subjects', models.ManyToManyField(related_name='exams', to='subjects.subject', verbose_name='考试科目')),
            ],
            options={
                'verbose_name': '考试',
                'verbose_name_plural': '考试',
                'db_table': 'exams',
                'ordering': ['-exam_date', '-created_at'],
            },
        ),
    ]
