# Generated by Django 5.2.8 on 2025-11-08 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamGradeSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(help_text='1-6年级', verbose_name='年级')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_subjects', to='exams.exam', verbose_name='考试')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject', verbose_name='科目')),
            ],
            options={
                'verbose_name': '考试年级科目',
                'verbose_name_plural': '考试年级科目',
                'db_table': 'exam_grade_subjects',
                'ordering': ['exam', 'grade', 'subject'],
                'unique_together': {('exam', 'grade', 'subject')},
            },
        ),
    ]
