# Generated by Django 5.2.8 on 2025-12-09 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_exam_created_by'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='schools.school', verbose_name='所属学校'),
        ),
    ]
