# Generated by Django 5.2.7 on 2025-11-05 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='科目名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='科目代码')),
                ('description', models.TextField(blank=True, null=True, verbose_name='科目描述')),
                ('applicable_grades', models.JSONField(default=list, help_text='例如：[1,2,3,4,5,6] 表示适用于所有年级', verbose_name='适用年级')),
                ('full_score', models.DecimalField(decimal_places=1, default=100.0, max_digits=5, verbose_name='满分')),
                ('pass_score', models.DecimalField(decimal_places=1, default=60.0, max_digits=5, verbose_name='及格分数')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '科目',
                'verbose_name_plural': '科目',
                'db_table': 'subjects',
                'ordering': ['order', 'id'],
            },
        ),
    ]
