# Generated by Django 5.2.7 on 2025-11-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='excellent_score',
            field=models.DecimalField(decimal_places=1, default=90.0, max_digits=5, verbose_name='优秀分数'),
        ),
    ]
