# Generated by Django 5.2.7 on 2025-11-05 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='班级名称')),
                ('grade', models.IntegerField(choices=[(1, '一年级'), (2, '二年级'), (3, '三年级'), (4, '四年级'), (5, '五年级'), (6, '六年级')], verbose_name='年级')),
                ('class_number', models.IntegerField(verbose_name='班号')),
                ('academic_year', models.CharField(default='2024-2025', max_length=20, verbose_name='学年')),
                ('semester', models.CharField(default='第二学期', max_length=10, verbose_name='学期')),
                ('student_count', models.IntegerField(default=0, verbose_name='学生人数')),
                ('classroom', models.CharField(blank=True, max_length=50, null=True, verbose_name='教室位置')),
                ('description', models.TextField(blank=True, null=True, verbose_name='班级描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
                'db_table': 'classes',
                'ordering': ['grade', 'class_number'],
            },
        ),
    ]
