# Generated by Django 5.2.7 on 2025-11-05 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='head_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'head_teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_teacher_classes', to=settings.AUTH_USER_MODEL, verbose_name='班主任'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('grade', 'class_number', 'academic_year', 'semester')},
        ),
    ]
