# Generated by Django 5.2.8 on 2025-11-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='academic_year',
            field=models.CharField(default='2025-2026', max_length=20, verbose_name='学年'),
        ),
        migrations.AlterField(
            model_name='class',
            name='semester',
            field=models.CharField(default='第一学期', max_length=10, verbose_name='学期'),
        ),
    ]
