# Generated by Django 5.2.8 on 2025-12-21 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_class_school'),
        ('schools', '0002_school_category_school_city_school_district_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('school', 'grade', 'class_number', 'academic_year', 'semester')},
        ),
    ]
