# Generated by Django 5.2.8 on 2025-12-21 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_alter_class_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.CharField(max_length=8, unique=True, verbose_name='邀请码')),
                ('subject_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='科目名称')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('max_uses', models.IntegerField(default=10, verbose_name='最大使用次数')),
                ('used_count', models.IntegerField(default=0, verbose_name='已使用次数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='classes.class', verbose_name='班级')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_invitations', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '班级邀请码',
                'verbose_name_plural': '班级邀请码',
                'db_table': 'class_invitations',
                'ordering': ['-created_at'],
            },
        ),
    ]
