# Generated by Django 5.2.8 on 2025-12-24 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_classinvitation'),
        ('students', '0007_add_vacation_setting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='小组名称')),
                ('color', models.CharField(default='#409EFF', help_text='用于UI展示的颜色标识', max_length=20, verbose_name='小组颜色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='classes.class', verbose_name='班级')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '学生分组',
                'verbose_name_plural': '学生分组',
                'db_table': 'student_groups',
                'ordering': ['class_obj', 'name'],
                'unique_together': {('class_obj', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StudentGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='classes.studentgroup', verbose_name='所属小组')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='students.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '小组成员',
                'verbose_name_plural': '小组成员',
                'db_table': 'student_group_members',
                'unique_together': {('group', 'student')},
            },
        ),
    ]
