# Generated by Django 5.2.8 on 2026-02-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_studentgroup_studentgroupmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='student_invite_code',
            field=models.CharField(blank=True, default='', help_text='学生通过此邀请码绑定账号', max_length=6, verbose_name='学生邀请码'),
        ),
    ]
