# Generated by Django 5.2.8 on 2026-02-21 07:44

import random
import string
from django.db import migrations


def populate_invite_codes(apps, schema_editor):
    Class = apps.get_model('classes', 'Class')
    existing_codes = set(
        Class.objects.exclude(student_invite_code='')
        .values_list('student_invite_code', flat=True)
    )
    for cls in Class.objects.filter(student_invite_code=''):
        for _ in range(100):
            code = ''.join(random.choices(string.digits, k=6))
            if code not in existing_codes:
                cls.student_invite_code = code
                cls.save(update_fields=['student_invite_code'])
                existing_codes.add(code)
                break


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_class_student_invite_code'),
    ]

    operations = [
        migrations.RunPython(populate_invite_codes, migrations.RunPython.noop),
    ]
