# Generated by Django 5.2.8 on 2026-02-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_populate_student_invite_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='student_invite_code',
            field=models.CharField(blank=True, help_text='学生通过此邀请码绑定账号', max_length=6, unique=True, verbose_name='学生邀请码'),
        ),
    ]
