# Generated by Django 5.2.8 on 2026-03-06 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_class_student_invite_code_unique'),
        ('schools', '0002_school_category_school_city_school_district_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('school', 'grade', 'class_number')},
        ),
        migrations.RemoveField(
            model_name='class',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='class',
            name='semester',
        ),
    ]
