# Generated by Django 5.2.7 on 2025-11-05 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='学号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=10, verbose_name='性别')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('id_number', models.CharField(blank=True, max_length=18, null=True, verbose_name='身份证号')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='联系电话')),
                ('parent_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='家长姓名')),
                ('parent_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='家长电话')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='家庭住址')),
                ('admission_date', models.DateField(blank=True, null=True, verbose_name='入学日期')),
                ('enrollment_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='入学方式')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='students/avatars/', verbose_name='头像')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否在读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='classes.class', verbose_name='班级')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
                'db_table': 'students',
                'ordering': ['class_obj__grade', 'class_obj__class_number', 'student_id'],
            },
        ),
    ]
