# Generated by Django 5.2.7 on 2025-11-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='入学年份'),
        ),
    ]
