# Generated by Django 5.2.8 on 2025-11-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_admission_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduatedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, verbose_name='学号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=10, verbose_name='性别')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('id_number', models.CharField(blank=True, max_length=18, null=True, verbose_name='身份证号')),
                ('graduation_year', models.CharField(max_length=20, verbose_name='毕业学年')),
                ('graduation_class_name', models.CharField(max_length=50, verbose_name='毕业班级')),
                ('graduation_grade', models.IntegerField(default=6, verbose_name='毕业年级')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='联系电话')),
                ('parent_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='家长姓名')),
                ('parent_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='家长电话')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='家庭住址')),
                ('admission_date', models.DateField(blank=True, null=True, verbose_name='入学日期')),
                ('admission_year', models.IntegerField(blank=True, null=True, verbose_name='入学年份')),
                ('enrollment_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='入学方式')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='graduated/avatars/', verbose_name='头像')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('graduation_date', models.DateField(auto_now_add=True, verbose_name='归档日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '毕业生',
                'verbose_name_plural': '毕业生',
                'db_table': 'graduated_students',
                'ordering': ['-graduation_year', 'student_id'],
                'indexes': [models.Index(fields=['graduation_year'], name='graduated_s_graduat_9bbcb8_idx'), models.Index(fields=['student_id'], name='graduated_s_student_68e07f_idx')],
            },
        ),
    ]
