# Generated by Django 5.2.8 on 2025-12-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_graduatedstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='learning_beans',
            field=models.IntegerField(default=0, verbose_name='学习豆'),
        ),
    ]
