# Generated by Django 5.2.8 on 2025-12-20 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_learning_beans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=20, verbose_name='学号'),
        ),
    ]
