# Generated by Django 5.2.8 on 2025-12-22 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_classinvitation'),
        ('students', '0005_unified_content_architecture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('positive', '正面表现'), ('negative', '需改进'), ('neutral', '中性记录')], default='positive', max_length=20, verbose_name='记录类型')),
                ('category', models.CharField(choices=[('recite', '背诵'), ('dictation', '默写'), ('reading', '认读'), ('discipline', '纪律'), ('labor', '劳动'), ('morality', '品德'), ('study', '学习'), ('other', '其他')], default='other', max_length=20, verbose_name='分类')),
                ('content', models.TextField(verbose_name='内容描述')),
                ('source', models.CharField(choices=[('manual', '手动录入'), ('system', '系统生成')], default='manual', max_length=20, verbose_name='来源')),
                ('source_detail', models.JSONField(blank=True, help_text='系统来源的详细信息，如关联的默写场次ID等', null=True, verbose_name='来源详情')),
                ('record_date', models.DateField(verbose_name='记录日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_records', to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_records', to='students.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '学生日常记录',
                'verbose_name_plural': '学生日常记录',
                'db_table': 'student_daily_records',
                'ordering': ['-record_date', '-created_at'],
                'indexes': [models.Index(fields=['student', 'record_date'], name='student_dai_student_37598d_idx'), models.Index(fields=['record_type', 'record_date'], name='student_dai_record__cbf8a9_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentSpotlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('daily', '每日之星'), ('weekly', '每周之星'), ('monthly', '每月之星')], default='daily', max_length=20, verbose_name='周期类型')),
                ('spotlight_date', models.DateField(verbose_name='生效日期')),
                ('source', models.CharField(choices=[('auto', '系统自动'), ('recommend', '教师推荐')], default='auto', max_length=20, verbose_name='选取来源')),
                ('recommend_reason', models.TextField(blank=True, help_text='教师推荐时填写的理由', verbose_name='推荐理由')),
                ('achievements', models.JSONField(default=list, help_text='格式: [{"type": "recite", "title": "背诵达人", "detail": "本周完成3篇古诗"}]', verbose_name='亮点列表')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='教师寄语')),
                ('is_displayed', models.BooleanField(default=False, verbose_name='是否已展示')),
                ('displayed_at', models.DateTimeField(blank=True, null=True, verbose_name='展示时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spotlights', to='classes.class', verbose_name='班级')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_spotlights', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spotlights', to='students.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '学生之星',
                'verbose_name_plural': '学生之星',
                'db_table': 'student_spotlights',
                'ordering': ['-spotlight_date', '-created_at'],
                'indexes': [models.Index(fields=['class_obj', 'spotlight_date', 'period'], name='student_spo_class_o_7943c6_idx'), models.Index(fields=['student', 'spotlight_date'], name='student_spo_student_6990c0_idx')],
                'unique_together': {('student', 'class_obj', 'period', 'spotlight_date')},
            },
        ),
    ]
