# Generated by Django 5.2.8 on 2025-12-22 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_category_school_city_school_district_and_more'),
        ('students', '0006_add_student_records_and_spotlights'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='如：2024-2025', max_length=20, verbose_name='学年')),
                ('vacation_type', models.CharField(choices=[('winter', '寒假'), ('summer', '暑假')], max_length=10, verbose_name='假期类型')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_settings', to='schools.school', verbose_name='学校')),
            ],
            options={
                'verbose_name': '假期设置',
                'verbose_name_plural': '假期设置',
                'db_table': 'vacation_settings',
                'ordering': ['-academic_year', 'vacation_type'],
                'unique_together': {('school', 'academic_year', 'vacation_type')},
            },
        ),
    ]
