# Generated by Django 5.2.8 on 2025-12-30 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_add_vacation_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='变动数量')),
                ('source', models.CharField(choices=[('dictation', '听写'), ('reading', '认读'), ('comment', '课堂点评'), ('correction', '数据修正')], max_length=20, verbose_name='来源')),
                ('detail', models.CharField(blank=True, max_length=200, verbose_name='详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bean_logs', to='students.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '学豆变动日志',
                'verbose_name_plural': '学豆变动日志',
                'db_table': 'student_bean_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'created_at'], name='student_bea_student_eab6d0_idx'), models.Index(fields=['source', 'created_at'], name='student_bea_source_cb2fd5_idx')],
            },
        ),
    ]
